Add the IExtractorRequest interface to alter requests
stadt-karlsruhe/ckanext-extractor pull request #5
Opened 2017-04-27 14:08 UTC by metaodi

In order to change requests before downloading files, this commit
introduces a new interface, which provides a hook to make arbitrary
changes to the request object before the request is actually sent.

2017-05-03 07:35 UTC, metaodi commented
@torfsen do you have any feedback on this PR?

2017-05-04 06:00 UTC, torfsen commented
@metaodi The PR looks fine -- however, I don't really understand the need for such a feature. Shouldn't a resource's URL be enough to access it?

2017-05-04 06:09 UTC, torfsen requested changes

2017-05-04 06:09 UTC, torfsen commented on ckanext/extractor/interfaces.py
> +        return request
The docs should mention that you need to return a request (which could be the original one after modifying it).

2017-05-04 06:09 UTC, torfsen commented on ckanext/extractor/interfaces.py
> +
Unnecessary empty line.

2017-05-04 06:09 UTC, torfsen commented on README.rst
> +  `from the requests library <http://docs.python-requests.org/en/master/user/advanced/#prepared-requests>`_.
Nitpicking: In reST, content between backticks can contain line-breaks:

    is a ``PreparedRequest`` object `from the requests library
    <http://docs.python-requests.org/en/master/user/advanced/#prepared-requests>`_.

2017-05-04 06:32 UTC, metaodi commented
@torfsen In my particular case, I need to provide an HTTP Authorization token to access the content of certain URLs, so no a resource URL alone is not enough. I can think of a number of other use cases like setting Accept headers to influence the format of the resource before it gets extracted or rewriting the URL to an internal server.

2017-05-04 07:11 UTC, metaodi reviewed
I updated the PR according to your comments.

2017-05-04 07:11 UTC, metaodi commented on README.rst
> +  `from the requests library <http://docs.python-requests.org/en/master/user/advanced/#prepared-requests>`_.
Done.

2017-05-04 07:11 UTC, metaodi commented on ckanext/extractor/interfaces.py
> +
Done.

2017-05-04 07:11 UTC, metaodi commented on ckanext/extractor/interfaces.py
> +        return request
Done.

2017-05-05 07:02 UTC, torfsen approved these changes

2017-05-05 07:02 UTC, merged

2017-05-05 07:03 UTC, torfsen commented
Thanks for you work, @metaodi!

2017-05-10 09:54 UTC, torfsen commented
Released in version [0.3.0](https://github.com/stadt-karlsruhe/ckanext-extractor/releases/tag/v0.3.0).